name: Laravel CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring,pdo_mysql
        coverage: none

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Setup environment
      run: |
        # Usar .env.example si existe, sino crear uno básico
        if [ -f ".env.example" ]; then
          cp .env.example .env
        else
          echo "APP_NAME=CI" > .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
        fi

    - name: Generate key
      run: php artisan key:generate

    - name: Run tests
      run: ./vendor/bin/phpunit

    - name: Trigger Coolify deploy
      if: success()
      run: curl -X POST "${{ secrets.COOLIFY_WEBHOOK }}"
